full_name = input("Please enter your full name: ")
gender = input("Please enter your gender: ")
age = input("Please enter your age: ")
Fname = input("Please enter your father's full name: ")
Mname = input("Please enter your mother's maiden name: ")
nationality = input("Enter you nationality: ")
birthdate = input("Enter your date of birth: ")
birthplace = input("Enter your place of birth: ")
civil_status = input("Enter your civil status: ")
religion = input("Enter you religion: ")
skills = input("Enter your relevant skills: ")
hobbies = input("Enter your hobbies: ")
email_address = input("Please enter a valid e-mail address: ")
mobile_no = input("Please enter your mobile number: ")
print("Hi! I'm " , full_name , "\b.I am" , gender , "and I am" , age , "years old. My parents are" , Fname , "and" , Mname, "\b. I am" , nationality , "and was born on", birthdate , "at" , birthplace , "and am currently" , civil_status,"\b. My religion is" , religion , "and I am proficient in" , skills , "and not only that but I also like to do" , hobbies , "in my free time. If you have any more questions about me you can contact me through" , email_address , "or" , mobile_no , "\b, and that's all about me. Thank you!")